title: "Aether Atlas"
description: "Dominascriptorum's living domain ledger and web control panel."
baseurl: "" # no subfolder since you're using a custom domain
url: "https://atlas.omniversalmedia.info"
theme: minima

markdown: kramdown
highlighter: rouge

permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-titles-from-headings

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

# Navigation & Meta
author: Hawk Eye / Ethan Womack
email: contact@omniversalmedia.org
lang: en
timezone: America/Chicago

# Optional future extras
future: true
include: [".well-known", "_pages"]

# Custom stylesheet
sass:
  style: compressed

include:
  - assets/css/custom.css

collections:
  articles:
    output: true
    permalink: /articles/:title/

